# Generated by Django 4.2.6 on 2023-10-15 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/images/%Y-%m-%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'svg', 'jpeg', 'png'])], verbose_name='Image services'),
        ),
    ]
