# Generated by Django 4.2.6 on 2023-10-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано в: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновленно в: ')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('requirement', models.TextField(verbose_name='Requirements')),
                ('condition', models.TextField(verbose_name='Conditions')),
                ('contact', models.CharField(max_length=160, verbose_name='Contacts')),
                ('url_for_vacancy', models.URLField(verbose_name='Google form')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
