# Generated by Django 4.2.6 on 2023-11-07 23:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_vacancy_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='id',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='уникальный идентификатор'),
        ),
    ]
