# Generated by Django 4.2.6 on 2023-11-07 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_remove_vacancy_id_vacancy_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='uuid',
            new_name='id',
        ),
    ]
