# Generated by Django 4.2.6 on 2023-11-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_alter_vacancy_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='url_for_vacancy',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='address',
            field=models.CharField(default=1, max_length=100, verbose_name='Address'),
            preserve_default=False,
        ),
    ]
