# Generated by Django 4.2.6 on 2023-11-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_remove_vacancy_condition_remove_vacancy_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='google_form',
            field=models.URLField(default=1, verbose_name='Google Form'),
            preserve_default=False,
        ),
    ]
