# Generated by Django 4.2.6 on 2023-11-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_vacancy_google_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='address_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='address_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='address_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_ky',
            field=models.CharField(max_length=80, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_ru',
            field=models.CharField(max_length=80, null=True, verbose_name='Title'),
        ),
    ]
