# Generated by Django 4.2.6 on 2023-10-31 18:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='уникальный идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано в: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновленно в: ')),
                ('image', models.ImageField(upload_to='affiliate/', verbose_name='Изображение филиала')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('address_ru', models.CharField(max_length=100, null=True, verbose_name='Адрес')),
                ('address_en', models.CharField(max_length=100, null=True, verbose_name='Адрес')),
                ('address_ky', models.CharField(max_length=100, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='уникальный идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано в: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновленно в: ')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='hall/', verbose_name='Изображение зала')),
                ('price', models.ImageField(upload_to='price/', verbose_name='Изображение цен')),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_affiliate', to='price.affiliate', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
    ]
