# Generated by Django 4.2.6 on 2023-10-13 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='halllist',
            name='price_list',
        ),
        migrations.AddField(
            model_name='price',
            name='hall_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='price_list', to='price.halllist', verbose_name='hall'),
            preserve_default=False,
        ),
    ]
