# Generated by Django 4.2.6 on 2023-10-13 20:31

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_rename_hall_list_price_hall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='currency',
        ),
        migrations.AddField(
            model_name='price',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('SOM', 'SOM')], default=None, editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=10, verbose_name='price'),
        ),
    ]
