# Generated by Django 4.2.6 on 2023-10-13 20:43

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_remove_price_currency_price_price_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='from_hour',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price_currency',
        ),
        migrations.RemoveField(
            model_name='price',
            name='to',
        ),
        migrations.CreateModel(
            name='HourDelta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано в: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновленно в: ')),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('SOM', 'SOM')], default=None, editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=0, max_digits=10, verbose_name='price')),
                ('to', models.CharField(blank=True, max_length=255, null=True, verbose_name='to')),
                ('from_hour', models.CharField(blank=True, max_length=255, null=True, verbose_name='from')),
                ('price_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours_delta_list', to='price.price', verbose_name='price')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
