# Generated by Django 4.2.6 on 2023-11-04 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0005_remove_price_from_hour_remove_price_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано в: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновленно в: ')),
                ('name_of_hall', models.CharField(max_length=70, verbose_name='Название зала')),
                ('image', models.ImageField(upload_to='images/price/', verbose_name='Изображение')),
                ('price_image', models.ImageField(upload_to='images/price_in_depth/', verbose_name='Изображение прайсов')),
            ],
            options={
                'verbose_name': 'Описание прайса',
            },
        ),
        migrations.RemoveField(
            model_name='hourdelta',
            name='price_model',
        ),
        migrations.RemoveField(
            model_name='price',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='price',
            name='hour',
        ),
        migrations.AddField(
            model_name='price',
            name='image',
            field=models.ImageField(default=1, upload_to='images/price/', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='name',
            field=models.CharField(default=1, max_length=80, verbose_name='Улица'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HallList',
        ),
        migrations.DeleteModel(
            name='HourDelta',
        ),
        migrations.AddField(
            model_name='price',
            name='privilege',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='price_privilege', to='price.privilege', verbose_name='Подробное описание зала'),
            preserve_default=False,
        ),
    ]
