# Generated by Django 4.2.6 on 2023-11-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0006_privilege_remove_hourdelta_price_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='privilege',
        ),
    ]
