# Generated by Django 4.2.6 on 2023-11-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0007_remove_price_privilege'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='privilege',
            field=models.ManyToManyField(related_name='privilege', to='price.privilege'),
        ),
    ]
