# Generated by Django 4.2.6 on 2023-11-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0008_price_privilege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/price/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/price/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='price_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/price_in_depth/', verbose_name='Изображение прайсов'),
        ),
    ]
