# Generated by Django 4.2.6 on 2023-11-04 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0009_alter_price_image_alter_privilege_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privilege',
            options={'verbose_name': 'Описание прайса', 'verbose_name_plural': 'Описание прайсов'},
        ),
        migrations.RemoveField(
            model_name='price',
            name='privilege',
        ),
        migrations.AddField(
            model_name='price',
            name='privilege',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='privilege', to='price.privilege'),
            preserve_default=False,
        ),
    ]
