# Generated by Django 4.2.6 on 2023-11-07 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0010_alter_privilege_options_remove_price_privilege_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано в: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновленно в: ')),
                ('name', models.CharField(max_length=80, verbose_name='Улица')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/price/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Прайс',
                'verbose_name_plural': 'Прайсы',
            },
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.AddField(
            model_name='privilege',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='privilege_price', to='price.location', verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
