# Generated by Django 4.2.6 on 2023-11-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0012_remove_privilege_location_location_privilege'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='privilege',
        ),
        migrations.AddField(
            model_name='location',
            name='privilege',
            field=models.ManyToManyField(related_name='privilege_location', to='price.privilege', verbose_name='Описание прайса'),
        ),
    ]
