# Generated by Django 4.2.6 on 2023-11-07 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0013_remove_location_privilege_location_privilege'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privilege',
            old_name='name_of_hall',
            new_name='name',
        ),
    ]
