# Generated by Django 4.2.6 on 2023-11-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0014_rename_name_of_hall_privilege_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='street',
        ),
        migrations.AddField(
            model_name='location',
            name='street_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='location',
            name='street_ky',
            field=models.CharField(max_length=80, null=True, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='location',
            name='street_ru',
            field=models.CharField(max_length=80, null=True, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='name_en',
            field=models.CharField(max_length=70, null=True, verbose_name='Название зала'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='name_ky',
            field=models.CharField(max_length=70, null=True, verbose_name='Название зала'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='name_ru',
            field=models.CharField(max_length=70, null=True, verbose_name='Название зала'),
        ),
    ]
