# Generated by Django 4.2.6 on 2023-10-31 18:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=60, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=60, null=True, verbose_name='Title')),
                ('title_ky', models.CharField(max_length=60, null=True, verbose_name='Title')),
                ('icon', models.ImageField(upload_to='contact/icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'ico'])], verbose_name='Icon')),
                ('link', models.URLField(verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='уникальный идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано в: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновленно в: ')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KG', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='уникальный идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано в: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновленно в: ')),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_affiliate', to='price.affiliate', verbose_name='Филиал')),
                ('affiliate_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_affiliate', to='price.affiliate', verbose_name='Филиал')),
                ('affiliate_ky', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_affiliate', to='price.affiliate', verbose_name='Филиал')),
                ('affiliate_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_affiliate', to='price.affiliate', verbose_name='Филиал')),
                ('phone', models.ManyToManyField(related_name='contact_phones', to='contact.phone', verbose_name='Phones')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
