# Generated by Django 4.2.6 on 2023-10-24 10:54

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('icon', models.ImageField(upload_to='contact/icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'ico'])], verbose_name='Icon')),
                ('link', models.URLField(verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано в: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновленно в: ')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KG', verbose_name='Phone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано в: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновленно в: ')),
                ('street', models.TextField(verbose_name='Street')),
            ],
            options={
                'verbose_name': 'Street',
                'verbose_name_plural': 'Streets',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано в: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновленно в: ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('links', models.ManyToManyField(related_name='contact_links', to='contact.link', verbose_name='Links')),
                ('phones', models.ManyToManyField(related_name='contact_phone', to='contact.phone', verbose_name='Phone')),
                ('streets', models.ManyToManyField(related_name='contact_street', to='contact.street', verbose_name='Street')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
