# Generated by Django 4.2.6 on 2023-11-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_contact_created_at_remove_contact_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Телефон', 'verbose_name_plural': 'Телефоны'},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'verbose_name': 'Улица', 'verbose_name_plural': 'Улицы'},
        ),
    ]
