# Generated by Django 4.2.6 on 2023-11-07 23:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_link_options_alter_phone_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='уникальный идентификатор'),
        ),
        migrations.AlterField(
            model_name='street',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='уникальный идентификатор'),
        ),
    ]
