# Generated by Django 4.2.6 on 2023-11-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_phone_id_alter_street_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано в: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновленно в: ')),
                ('address', models.TextField(verbose_name='Street')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phones',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='streets',
        ),
        migrations.RemoveField(
            model_name='link',
            name='icon',
        ),
        migrations.AlterField(
            model_name='phone',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Street',
        ),
        migrations.AddField(
            model_name='address',
            name='phones',
            field=models.ManyToManyField(related_name='street_phone', to='contact.phone', verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='contact',
            name='addresses',
            field=models.ManyToManyField(related_name='contact_address', to='contact.address', verbose_name='Адрес'),
        ),
    ]
