# Generated by Django 4.2.6 on 2023-11-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_remove_link_title_link_social_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_en',
            field=models.TextField(null=True, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='address',
            name='address_ky',
            field=models.TextField(null=True, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='address',
            name='address_ru',
            field=models.TextField(null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='link',
            name='social_media',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('TikTok', 'TikTok'), ('WhatsApp', 'WhatsApp'), ('Telegram', 'Telegram')], default='Telegram', max_length=17, verbose_name='Соц.Сети'),
        ),
    ]
