# Generated by Django 4.2.6 on 2023-11-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_address_address_en_address_address_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='geolocation_address',
            field=models.URLField(default=1, verbose_name='Address_url'),
            preserve_default=False,
        ),
    ]
